language: ruby
sudo: false
cache: bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle update

rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

env:
  global:
    - TEST=true

script:
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r 4e65a8cf75d0dd2b0cdc5b469fb54f963d270540041816f7a754af085bf9b2ae
