language: ruby
sudo: false
cache: bundler

before_install:
  - gem install bundler # https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-373042916

before_script:
  - bundle update

rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

env:
  global:
    - TEST=true

script: bundle exec rake
